#!/bin/bash
usage(){
  echo "$0: <port number>" 2>&1
  exit 1
}
if (( $# != 1 )); then
  usage
fi
port=$1
out=$(lsof -i:$port)
count=$( $out | wc -l )
if (( $count==0 )); then exit 0; fi
echo "$0: $count ports listening on port $port"
echo "$out"
